FROM qq275860560/datax

MAINTAINER jiangyuanlin@163.com

RUN cd /tmp &&  git clone https://github.com/qq275860560/dataxweb.git

CMD source /etc/profile &&\
     service sshd start &&\
     service dataxweb start 	

 
